export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "./styles/globals.css";
import Navbar from "../components/Navbar/Navbar"
import Preloader from '../components/Preloader/Preloader';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Preloader></Preloader> 
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
