import "@/styles/globals.css";
import { Navbar } from "@/components";

export const metadata = {
  title: 'SASB',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
            {children}
      </body>
    </html>
  )
}
